apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Chart.Name }}-api
    labels:
        app: {{ .Chart.Name }}-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Chart.Name }}-api
    template:
        metadata:
            labels:
                app: {{ .Chart.Name }}-api
        spec:
            containers:
                - name: {{ .Chart.Name }}-api
                  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
                  ports:
                      - containerPort: 8080
            imagePullSecrets:
                - name: dockersecret
