apiVersion: v1
kind: Secret
metadata:
  name: dockersecret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoianBtYWNhcnRodXIiLCJwYXNzd29yZCI6ImdocF9pTFFoM0VRcXRrTHE3bWduZjR2ZnAwSGxTTFJ6NlAya1hzSU8iLCJlbWFpbCI6ImpwbUBwbWFjYXJ0aHVyLmNvbSIsImF1dGgiOiJhbkJ0WVdOaGNuUm9kWEk2WjJod1gybE1VV2d6UlZGeGRHdE1jVGR0WjI1bU5IWm1jREJJYkZOTVVubzJVREpyV0hOSlR3PT0ifX19
type: kubernetes.io/dockerconfigjson