kind: Service
apiVersion: v1
metadata:
    name: {{ .Chart.Name }}-api-svc
    labels:
        app: {{ .Chart.Name }}-api
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    selector:
        app: {{ .Chart.Name }}-api
status:
    loadBalancer:
        ingress:
        - ip: 192.168.1.112