kind: Service
apiVersion: v1
metadata:
    name: mongo-svc
    labels:
        app: mongo
spec:
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
    selector:
        app: mongo
status:
    loadBalancer:
        ingress:
        - ip: 192.168.1.115